### ISSUE TITLE
[docs] Add HLJS

### ISSUE THREAD

**Issue by budparr** [budparr/gohugo-theme#1]
Not sure yet I understand how it works.

**Comment by rdwatters** [comment]
Not sure how progress is coming along on this @budparr but as an FYI, I extended the HLJS for some hugo-specific needs if you look at the code. LMK if you have any questions, brother. Thanks!

**Comment by budparr** [comment]
So, reviewing this file: 
https://github.com/rdwatters/hugo-docs-concept/blob/master/themes/hugo-docs-concept/pipeline/js/scripts/highlight.pack.js

It looks like this is a hand copied file with no dependencies, correct? Can you point out exactly what you added so I can pull that out. I'm going to try to use NPM and just add the critical bits, which I think will make it more maintainable in the future.

**Comment by budparr** [comment]
This is where I'm at so far:
https://github.com/budparr/gohugo-theme/blob/master/src/js/hljs.js

**Comment by budparr** [comment]
- [ ] pick a different style

**Comment by budparr** [comment]
- [ ] check, it may have created a conflict with my copy button styling

**Comment by budparr** [comment]
I spoofed HLJS by registering the handlebars library for HTML, which allows us to highlight just the Hugo templating. I've styled it so just that shows up. May have to adjust, but I think this makes sense. 

<img width="571" alt="screen shot 2017-04-27 at 11 50 55 pm" src="https://cloud.githubusercontent.com/assets/115347/25513615/70175344-2ba4-11e7-99db-081a4a481f0b.png">

_FWIW, @rdwatters, we have a lot of opinionated HTML in there that doesn't really belong. This one in the image is a case in point, where it has ID selectors, which don't need to be there, and are bad practice anyway. I can make an issue on the other repo later, just brought up it because I've been looking at these code blocks all night_

**Comment by rdwatters** [comment]
I was going to write and mention that you can probably just download the HLJS with the languages I already include in the current version and just don't worry about the tweaks I made, some of which were just to make HLJS render the corresponding icon as part of the fontello icon font. 

Agreed on some of the opinionated selectors, many of which are just carried over from the current site where we have some old (and many outdated examples pulled from spf13's site). As far as the ID being a bad practice, I agree for CSS, but it's still the fastest way to grab an element from the DOM using JS because of the way the browser indexes the elements (this might be outdated though). But that's neither here nor there - the main point is that we should use classes if the facilitate understanding of the concept...or do you think

**Comment by budparr** [comment]
I just think the bare minimum HTML to be illustrative (the rest is noise, IMHO), and I don't see any reason for class or IDs, unless they have something specific to do with what's being illustrated. 

```
{{ partial "header.html" . }}
{{ partial "subheader.html" . }}

<section>
  <h1>{{ .Title }}</h1>
  <ul>
    {{ range .Data.Pages }}
       {{ .Render "li"}}
    {{ end }}
  </ul>
</section>
{{ partial "footer.html" . }}
```

**Comment by rdwatters** [comment]
Good call. I'll update this weekend. There are only a couple examples where I think classes may help, but these might be better served with just a few HTML comments. Cheers!

**Comment by budparr** [comment]
Cool. I'm going to close this for now. We may want to revisit the styling, but that's easy enough, so if you see something that needs some color (as I said, I only styled the Hugo tags), just drop an issue. 

Thanks!
